name: Build Weekly Digest

permissions:
  contents: write

on:
  schedule:
    - cron: "0 16 * * MON"   # Mondays 09:00 Phoenix
  workflow_dispatch:

concurrency:
  group: newsletter
  cancel-in-progress: false

jobs:
  newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Make newsletter
        run: python scripts/make_newsletter.py
      - name: Commit & push
        run: |
          git config user.name "cf-bot"
          git config user.email "cf-bot@users.noreply.github.com"
          git add newsletter.md
          git commit -m "newsletter: weekly digest [skip ci]" || echo "No changes"
          git push
