name: Build X-only RSS

on:
  push:
    branches: [ main ]      # change if your default branch differs
    paths:
      - 'rss.xml'           # only run when the main feed changes
  workflow_dispatch:

jobs:
  build-x-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ensure script is present
        run: |
          test -f scripts/make_x_feed.py || (echo "scripts/make_x_feed.py missing" && exit 1)

      - name: Build X-only RSS (rss_x.xml)
        run: python scripts/make_x_feed.py

      # Optional: keep temporarily while dialing in length reserves
      - name: Debug: show length of latest X item
        run: |
          python - <<'PY'
          import xml.etree.ElementTree as ET
          t=ET.parse('rss_x.xml')
          ch=t.getroot().find('channel')
          items=ch.findall('item')
          if not items:
              print("No items in X feed"); raise SystemExit
          it=items[0]  # latest is typically first; adjust if your order differs
          title=(it.findtext('title') or '')
          print("TITLE LEN:", len(title))
          print("TITLE TEXT:", title[:220] + ('...' if len(title)>220 else ''))
          print("LINK:", (it.findtext('link') or ''))
          PY

      - name: Commit rss_x.xml if changed
        run: |
          if git diff --quiet rss_x.xml; then
            echo "No changes to rss_x.xml"
          else
            git config user.name "cf-bot"
            git config user.email "cf-bot@users.noreply.github.com"
            git add rss_x.xml
            git commit -m "Build/Update rss_x.xml [skip ci]" || echo "Nothing to commit"
            git push
          fi
